# Generated by Django 4.2.1 on 2023-06-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=30)),
                ('identification', models.CharField(max_length=8)),
                ('password', models.CharField(max_length=20)),
                ('payment', models.DecimalField(decimal_places=3, max_digits=20)),
            ],
        ),
    ]
