# Generated by Django 4.2.4 on 2023-08-19 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='payment',
        ),
    ]
