# Generated by Django 4.2.3 on 2023-07-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orders_customer'),
        ('shipment', '0003_shipment_customer_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='customer_order',
        ),
        migrations.AddField(
            model_name='shipment',
            name='customer_order',
            field=models.ManyToManyField(to='orders.orders'),
        ),
    ]
