# Generated by Django 4.2.3 on 2023-07-31 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0004_remove_shipment_customer_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='phone_number',
        ),
    ]
