# Generated by Django 4.2.1 on 2023-06-21 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_note', models.TextField()),
                ('transaction_id', models.IntegerField()),
                ('order', models.CharField(max_length=24)),
                ('products', models.CharField(max_length=32)),
            ],
        ),
    ]
