# Generated by Django 4.2.3 on 2023-07-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='order',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='products',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_note',
            field=models.CharField(max_length=48),
        ),
    ]
