# Generated by Django 4.2.3 on 2023-07-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.CharField(max_length=28)),
                ('number_of_items', models.IntegerField()),
                ('payment', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
