# Generated by Django 4.2.3 on 2023-07-07 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_name_of_product_remove_cart_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='name_of_product',
        ),
    ]
