# Generated by Django 4.2.3 on 2023-07-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_remove_cart_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='category',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
