# Generated by Django 4.2.3 on 2023-07-08 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_orders_order_id_remove_orders_payment_and_more'),
        ('cart', '0008_cart_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.orders'),
            preserve_default=False,
        ),
    ]
