# Generated by Django 4.2.3 on 2023-07-14 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_alter_cart_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='order',
            new_name='product_order',
        ),
    ]
