# Generated by Django 4.2.3 on 2023-07-07 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
    ]
