# Generated by Django 4.2.3 on 2023-07-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orders_customer_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='customer_order',
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.IntegerField(),
        ),
    ]
