# Generated by Django 4.2.3 on 2023-07-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_vendor'),
        ('orders', '0005_remove_orders_customer_order_alter_orders_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='payment',
        ),
        migrations.AddField(
            model_name='orders',
            name='products',
            field=models.ManyToManyField(to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.BooleanField(),
        ),
    ]
