# Generated by Django 4.2.3 on 2023-07-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_user'),
        ('orders', '0007_remove_orders_products_orders_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='customer',
            field=models.ManyToManyField(to='customer.customer'),
        ),
    ]
